[package]
name = "jitted"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
utf = []
asm = []
boehm = []
sgen = []

[dependencies]
dynasmrt = "1.2.3"
itoa = "1.0.3"
ryu = "1.0.11"
simdutf = "0.3.0"

[profile.release]
lto = true
